# Generated by Django 5.0.6 on 2024-07-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioadl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='desafioadl.tarea'),
        ),
    ]
